name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Execute
      run: cd aoc_1 && cargo run --verbose
    - name: Tests
      run: cd aoc_1 && cargo test --verbose
